namespace Testing.Dnn.ArmyManager.ArmyManager.ViewArmyManager
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;

    /// <summary>
    /// Overall data structure Army- has a collection of Units, a Name, and a Max points value
    /// </summary>
    public class Army
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Army"/> class.
        /// Creates a new army with a single unit
        /// </summary>
        /// <param name="name">The name of the army, set by the user</param>
        /// <param name="points">the max points for the army set by the user</param>
        /// <param name="units">List of units to be initialized with the army</param>
        /// <param name="id">army ID generated by the server</param>
        public Army(string name, int points, List<Unit> units, int id )
        {
            this.ArmyName = name;
            this.MaxPoints = points;
            this.Units = units;
            this.ArmyID = id;
        }

        private int ArmyID { get; set; }

        private string ArmyName { get; set; }

        private int MaxPoints { get; set; }

        private IEnumerable<Unit> Units { get; set; }
    }
}